// Series callbacks; visual designs and placements are authored for this game.
export const objects = {
 'four-naan': {name:'four naan',operation:'Portion control',brief:'Recover the takeaway order before Mark starts calculating naan per person.',room:'kitchen',found:'The order is intact. Mark still has questions about the quantities.',caption:'A perfectly ordinary takeaway order, provided nobody asks Mark to approve it.'},
 'christmas-cauliflower': {name:'the Christmas cauliflower',operation:'Vegetable dispute',brief:'Find the cauliflower. Apparently Christmas vegetables require a policy decision.',room:'kitchen',found:'The vegetable has been located. Its festive credentials remain under review.',caption:'A vegetable with no idea how much trouble it has caused.'},
 'heat-dvd': {name:'Heat on DVD',operation:'A quiet evening',brief:'Find the DVD for a quiet evening in. There may be admin first.',room:'living',found:'The film is ready. Someone will still talk over it.',caption:'A sensible film for a sensible evening. The flat may have other plans.'},
 'mark-shredder': {name:'Mark’s second-hand shredder',operation:'Gift economy',brief:'Locate the second-hand shredder. Practicality is a perfectly valid Christmas emotion.',room:'mark',found:'A useful appliance. Several complicated feelings.',caption:'Nothing says festive generosity quite like a previously owned office appliance.'},
 'sofa-receipt': {name:'the Creamy Elephant finance statement',operation:'Comfort on credit',brief:'Find the sofa paperwork. Mark would like sitting down to remain financially accountable.',room:'mark',found:'The Creamy Elephant’s repayments are accounted for.',caption:'The sofa is very comfortable. The repayment schedule less so.'},
 'jez-demo-tape': {name:'Jez’s demo tape',operation:'Recording career',brief:'Jez needs his homemade demo tape. His next big break is somewhere under yesterday’s clutter.',room:'jez',found:'A future musical sensation has been recovered. The music industry remains unaware.',caption:'One cassette. Several unfinished tracks. An extremely optimistic career plan.'},
 'red-toolbox': {name:'the red toolbox',operation:'Toolbox',brief:'A small domestic emergency. Someone needs the red toolbox.',room:'kitchen',found:'One minor domestic crisis resolved.',caption:'For all the jobs that will definitely get done next weekend.'},
 'jez-bong': {name:'Jez’s bong',operation:'Unfinished business',brief:'Jez has misplaced his bong. Again. Find it before he starts blaming Mark.',room:'jez',found:'Jez can stop accusing everyone else now.',caption:'An essential piece of equipment for a recording session that never quite starts.'},
 'pharaohs-book': {name:'Business Secrets of the Pharaohs',operation:'Literary ambition',brief:'Mark needs his copy of Business Secrets of the Pharaohs. His literary future depends on it.',room:'mark',found:'Mark’s literary ambitions are safe. For now.',caption:'Ancient Egypt. Modern management. A publishing empire waiting to happen.'},
 'hans-trainers': {name:'Super Hans’s trainers',operation:'Lost soles',brief:'Super Hans has left his trainers somewhere in the flat. Track them down.',room:'living',found:'Super Hans can leave with both shoes.',caption:'A pair of trainers with a past. Probably best not to ask about it.'},
 'rainbow-flyer': {name:'the Rainbow Rhythms flyer',operation:'Express yourself',brief:'Jez wants the Rainbow Rhythms flyer. Mark would prefer everyone forget the whole thing.',room:'jez',found:'The dance class is back on. Mark is already making an excuse.',caption:'A dance class where the only thing more awkward than joining in is explaining why you won’t.'},
 'jlb-pass': {name:'Mark’s JLB Credit pass',operation:'Back to business',brief:'Mark has lost his JLB Credit pass. Recover this small rectangle of professional self-worth.',room:'mark',found:'Mark’s professional identity has been restored.',caption:'A tiny plastic reminder that Mark had a proper job, proper colleagues and quite a lot of anxiety.'},
 'christmas-turkey': {name:'the Christmas turkey',operation:'Seasonal emergency',brief:'Find the Christmas turkey before Mark turns dinner into a full family incident.',room:'kitchen',found:'Christmas dinner has been saved. The atmosphere may take longer.',caption:'One turkey. The emotional stability of an entire Christmas dinner.'},
};
for(const [id,prop] of Object.entries(objects))prop.image=`assets/objects/${id}.png?v=8ff3ceb3dc77`;
export function pickTarget(previous,random=Math.random){const candidates=Object.keys(objects).filter(id=>id!==previous);return candidates[Math.min(candidates.length-1,Math.floor(random()*candidates.length))];}
